// Datos embebidos de historias de usuario
const EMBEDDED_DATA = {
  videoconference: {
    userStories: [
      {
        code: "US-1",
        title: "Sign-up básico",
        sprint: "S1",
        epic: "E-1 Gestión de cuentas",
        ux: 3,
        design: 5,
        front: 8,
        back: 5,
        description:
          "Como visitante de la plataforma\nQuiero registrarme con mis datos personales\nPara poder crear y unirme a reuniones de videoconferencia.",
        acceptanceCriteria: [
          "Visualización del formulario: al acceder a /signup se muestran los campos: Nombre completo, Correo electrónico, Contraseña (≥ 8 caracteres, mínimo 1 mayúscula, número y carácter especial) y Confirmar contraseña.",
          "Validación en tiempo real: el botón Registrarse permanece deshabilitado hasta que todos los campos sean válidos.",
          "Contraseña: ≥ 8 caracteres, al menos una mayúscula, una minúscula y un número.",
          "Confirmar contraseña coincide con Contraseña.",
          "Los mensajes de error se anuncian en una región aria-live='polite' y desaparecen al corregir el campo.",
          "Envío exitoso: al presionar Registrarse con datos válidos se muestra un spinner de procesamiento (máx. 3 s).",
          "Firebase Authentication responde con el uid del nuevo usuario.",
          "Se crea documento en Firestore users/{uid} con {email, displayName, createdAt, photoURL: null}.",
          "Se emite un toast 'Cuenta creada con éxito' y el usuario es redirigido a /dashboard en ≤ 500 ms.",
          "Manejo de errores: correo ya existe → 'Este correo ya está registrado'; errores de red → 'Intenta de nuevo más tarde' (log en consola en modo dev).",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "Documentación JSDoc añadida; README actualizado con el flujo de registro.",
          "Comprobado comportamiento responsivo en 320 px, 768 px y 1024 px mediante Chrome DevTools.",
          "Despliegue automático en Vercel (frontend) y Render (API) exitoso.",
          "Heurística 1: Visibilidad del estado del sistema implementada (spinner, toasts).",
        ],
      },
      {
        code: "US-2",
        title: "Login con credenciales",
        sprint: "S1",
        epic: "E-1 Gestión de cuentas",
        ux: 2,
        design: 5,
        front: 5,
        back: 5,
        description:
          "Como usuario registrado\nQuiero iniciar sesión con correo y contraseña\nPara acceder a mis reuniones y configuración.",
        acceptanceCriteria: [
          "Visualización del formulario: en /login se muestran los campos Correo electrónico y Contraseña más el enlace '¿Olvidaste tu contraseña?'.",
          "Validación en tiempo real: el botón Iniciar sesión permanece deshabilitado hasta que los campos sean válidos (correo formato RFC 5322, contraseña presente).",
          "Mensajes de error se anuncian en región aria-live='polite'.",
          "Autenticación exitosa: al presionar Iniciar sesión se muestra spinner (≤ 3 s).",
          "Firebase Authentication devuelve token válido por 1 hora que se almacena en secure localStorage.",
          "El usuario es redirigido a /dashboard en ≤ 500 ms y se muestra saludo 'Hola, Nombre'.",
          "Persistencia de sesión: al recargar la página, si el token no expiró, el usuario permanece en /dashboard.",
          "Acceso a rutas protegidas sin token redirige a /login.",
          "Manejo de errores: credenciales incorrectas → 'Correo o contraseña inválidos'; cuenta deshabilitada → 'Cuenta temporalmente deshabilitada'; errores de red → 'Inténtalo de nuevo más tarde'.",
          "Seguridad: se limita a 5 intentos fallidos por IP cada 10 min (respuesta 429).",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "Documentación JSDoc añadida; README actualizado con flujo de login.",
          "Responsivo validado en 320 px, 768 px y 1024 px.",
          "Despliegue en Vercel/Render exitoso; rutas /login accesibles vía HTTPS.",
          "Heurística 2: Coincidencia entre sistema y mundo real (mensajes claros).",
        ],
      },
      {
        code: "US-3",
        title: "Login con Google OAuth",
        sprint: "S1",
        epic: "E-1 Gestión de cuentas",
        ux: 1,
        design: 3,
        front: 5,
        back: 3,
        description:
          "Como usuario\nQuiero iniciar sesión con mi cuenta de Google\nPara acceder rápidamente sin crear una contraseña.",
        acceptanceCriteria: [
          "Botón 'Continuar con Google' visible en /login y /signup con icono oficial de Google.",
          "Al hacer clic se abre popup de autenticación OAuth de Google.",
          "Firebase Authentication maneja el flujo OAuth 2.0.",
          "Si el usuario no existe en Firestore, se crea documento users/{uid} con datos del perfil de Google.",
          "Si el usuario ya existe, se actualiza lastLoginAt.",
          "Redirige a /dashboard con toast 'Bienvenido, Nombre'.",
          "Manejo de errores: popup cerrado → mensaje 'Inicio de sesión cancelado'; error de red → 'Intenta de nuevo más tarde'.",
          "Cumplir con políticas de privacidad y términos de Google OAuth.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan flujo OAuth con Google.",
          "Responsivo probado en 320, 768, 1024 px.",
          "Despliegue exitoso; OAuth configurado en Firebase Console.",
          "WCAG 1: Alternativas textuales para imágenes (icono Google con alt).",
        ],
      },
      {
        code: "US-4",
        title: "Login con Facebook OAuth",
        sprint: "S1",
        epic: "E-1 Gestión de cuentas",
        ux: 1,
        design: 3,
        front: 5,
        back: 3,
        description:
          "Como usuario\nQuiero iniciar sesión con mi cuenta de Facebook\nPara acceder usando mis credenciales de redes sociales.",
        acceptanceCriteria: [
          "Botón 'Continuar con Facebook' visible en /login y /signup con icono oficial de Facebook.",
          "Al hacer clic se abre popup de autenticación OAuth de Facebook.",
          "Firebase Authentication maneja el flujo OAuth 2.0.",
          "Si el usuario no existe en Firestore, se crea documento users/{uid} con datos del perfil de Facebook.",
          "Si el usuario ya existe, se actualiza lastLoginAt.",
          "Redirige a /dashboard con toast 'Bienvenido, Nombre'.",
          "Manejo de errores: popup cerrado → 'Inicio de sesión cancelado'; error de red → 'Intenta de nuevo más tarde'.",
          "Cumplir con políticas de privacidad y términos de Facebook Login.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan flujo OAuth con Facebook.",
          "Responsivo probado en 320, 768, 1024 px.",
          "Despliegue exitoso; OAuth configurado en Firebase Console y Facebook Developers.",
          "Heurística 3: Control y libertad del usuario (opción de cancelar login).",
        ],
      },
      {
        code: "US-5",
        title: "Logout",
        sprint: "S1",
        epic: "E-1 Gestión de cuentas",
        ux: 1,
        design: 2,
        front: 3,
        back: 2,
        description:
          "Como usuario autenticado\nQuiero cerrar sesión de forma segura\nPara proteger mi cuenta cuando termine de usar la plataforma.",
        acceptanceCriteria: [
          "Botón 'Cerrar sesión' visible en menú de usuario (header o sidebar).",
          "Al hacer clic se ejecuta Firebase signOut().",
          "El token se elimina de localStorage.",
          "El usuario es redirigido a /login en ≤ 500 ms.",
          "Se muestra toast 'Sesión cerrada correctamente'.",
          "Cualquier intento de acceder a rutas protegidas redirige a /login.",
          "Manejo de errores: si falla el logout → mensaje 'Error al cerrar sesión' pero igual se redirige.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README actualizados con flujo de logout.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso en Vercel/Render.",
          "Heurística 4: Consistencia y estándares (botón logout en ubicación esperada).",
        ],
      },
      {
        code: "US-6",
        title: "Recuperar contraseña",
        sprint: "S1",
        epic: "E-1 Gestión de cuentas",
        ux: 2,
        design: 3,
        front: 5,
        back: 3,
        description:
          "Como usuario que olvidó su contraseña\nQuiero restablecerla mediante enlace por correo\nPara recuperar el acceso a mi cuenta.",
        acceptanceCriteria: [
          "En /forgot-password se muestra campo Correo electrónico con botón 'Enviar enlace'.",
          "Al ingresar correo válido se muestra spinner (≤ 3 s).",
          "Firebase sendPasswordResetEmail() envía correo con enlace válido 1 hora.",
          "Se muestra toast 'Revisa tu correo para continuar'.",
          "El enlace lleva a página de Firebase para restablecer contraseña.",
          "Al completar, Firebase actualiza la contraseña y redirige a /login.",
          "Manejo de errores: correo no registrado → respuesta genérica 'Si el correo existe, recibirás un enlace'; errores de red → 'Intenta de nuevo más tarde'.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README incluyen flujo de recuperación.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Correo de prueba recibido y enlace operativo.",
          "Despliegue exitoso; ruta /forgot-password accesible vía HTTPS.",
        ],
      },
      {
        code: "US-7",
        title: "Editar perfil de usuario",
        sprint: "S1",
        epic: "E-1 Gestión de cuentas",
        ux: 2,
        design: 5,
        front: 8,
        back: 5,
        description:
          "Como usuario autenticado\nQuiero modificar mi nombre y foto de perfil\nPara personalizar mi identidad en las reuniones.",
        acceptanceCriteria: [
          "En /profile se muestran campos editables: Nombre completo y botón 'Cambiar foto'.",
          "Al seleccionar 'Cambiar foto' se abre selector de archivo (jpg, png, max 5 MB).",
          "La foto se sube a Firebase Storage en /profile-pictures/{uid}.",
          "Se actualiza photoURL en Firestore users/{uid} y en Firebase Authentication.",
          "Validación: nombre no vacío, foto dentro del tamaño permitido.",
          "Al guardar cambios se muestra spinner (≤ 2 s) y toast 'Perfil actualizado'.",
          "Los cambios se reflejan inmediatamente en la UI sin recargar.",
          "Manejo de errores: foto muy grande → 'La imagen no debe superar 5 MB'; error de red → toast genérico.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README actualizados con flujo de edición de perfil.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; Storage configurado en Firebase.",
          "WCAG 2: Contenido adaptable (texto alternativo para foto de perfil).",
        ],
      },
      {
        code: "US-8",
        title: "Eliminar cuenta de usuario",
        sprint: "S1",
        epic: "E-1 Gestión de cuentas",
        ux: 2,
        design: 3,
        front: 5,
        back: 8,
        description:
          "Como usuario autenticado\nQuiero borrar definitivamente mi cuenta\nPara dejar de usar la plataforma y eliminar mis datos.",
        acceptanceCriteria: [
          "En /profile botón 'Eliminar cuenta' con estilo de advertencia.",
          "Al hacer clic se abre modal pidiendo confirmar escribiendo 'ELIMINAR' y contraseña actual.",
          "Se ejecuta Firebase delete() y se elimina documento users/{uid} de Firestore.",
          "Se eliminan todas las reuniones creadas por el usuario en meetings.",
          "Si el usuario tiene foto en Storage, se elimina también.",
          "Spinner (≤ 2 s), luego redirect a /login con toast 'Cuenta eliminada correctamente'.",
          "Manejo de errores: contraseña incorrecta → 'Contraseña inválida'; error de red → toast genérico.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README actualizados con flujo de eliminación.",
          "Responsivo probado en 320, 768, 1024 px.",
          "Despliegue exitoso; eliminación en cascada verificada.",
          "Heurística 5: Prevención de errores (modal de confirmación).",
        ],
      },
      {
        code: "US-9",
        title: "Crear reunión",
        sprint: "S1",
        epic: "E-2 Gestión de reuniones",
        ux: 3,
        design: 5,
        front: 8,
        back: 8,
        description:
          "Como usuario autenticado\nQuiero crear una nueva reunión con ID único\nPara compartir el enlace con otros participantes.",
        acceptanceCriteria: [
          "En /dashboard botón 'Crear reunión' prominente.",
          "Al hacer clic se genera un ID único alfanumérico de 10 caracteres.",
          "Se crea documento en Firestore meetings/{meetingId} con {hostId: uid, createdAt, participants: [], status: 'active'}.",
          "Se redirige a /meeting/{meetingId} en ≤ 500 ms.",
          "Se muestra toast 'Reunión creada' y opción para copiar enlace de invitación.",
          "El enlace tiene formato https://app.com/join/{meetingId}.",
          "Manejo de errores: error de red → 'No se pudo crear la reunión, intenta de nuevo'.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan flujo de creación de reunión.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; colección meetings creada en Firestore.",
          "Heurística 6: Reconocer en lugar de recordar (enlace fácil de compartir).",
        ],
      },
      {
        code: "US-10",
        title: "Unirse a reunión por ID",
        sprint: "S2",
        epic: "E-2 Gestión de reuniones",
        ux: 2,
        design: 3,
        front: 5,
        back: 5,
        description:
          "Como usuario autenticado\nQuiero unirme a una reunión ingresando su ID\nPara participar sin necesidad del enlace completo.",
        acceptanceCriteria: [
          "En /dashboard campo de texto 'ID de reunión' con botón 'Unirse'.",
          "Validación: ID debe tener 10 caracteres alfanuméricos.",
          "Al hacer clic se consulta Firestore meetings/{meetingId}.",
          "Si la reunión existe y está activa, redirige a /meeting/{meetingId}.",
          "Se añade uid a participants[] en el documento de la reunión.",
          "Si la reunión no existe → toast 'Reunión no encontrada'.",
          "Si la reunión está llena (10 participantes) → toast 'La reunión está llena'.",
          "Manejo de errores: ID inválido → 'ID inválido'; error de red → toast genérico.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README actualizados con flujo de unirse a reunión.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; validación de límite de participantes implementada.",
          "Heurística 7: Flexibilidad y eficiencia de uso (múltiples formas de unirse).",
        ],
      },
      {
        code: "US-11",
        title: "Unirse a reunión por enlace",
        sprint: "S2",
        epic: "E-2 Gestión de reuniones",
        ux: 1,
        design: 2,
        front: 5,
        back: 5,
        description:
          "Como usuario\nQuiero hacer clic en un enlace de invitación\nPara unirme directamente a una reunión.",
        acceptanceCriteria: [
          "Al acceder a /join/{meetingId} se valida si el usuario está autenticado.",
          "Si no está autenticado, redirige a /login con parámetro ?redirect=/join/{meetingId}.",
          "Después del login, redirige automáticamente a /meeting/{meetingId}.",
          "Si está autenticado, valida que la reunión exista y no esté llena.",
          "Se añade uid a participants[] y redirige a /meeting/{meetingId}.",
          "Manejo de errores igual que US-10.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan flujo de enlace de invitación.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; redirección post-login funciona correctamente.",
          "WCAG 3: Navegable (enlaces descriptivos y funcionales).",
        ],
      },
      {
        code: "US-12",
        title: "Ver lista de participantes",
        sprint: "S2",
        epic: "E-2 Gestión de reuniones",
        ux: 2,
        design: 5,
        front: 8,
        back: 5,
        description:
          "Como participante de una reunión\nQuiero ver quiénes están conectados\nPara saber quién está presente.",
        acceptanceCriteria: [
          "En /meeting/{meetingId} panel lateral o modal con lista de participantes.",
          "Se muestra nombre y foto de perfil de cada participante.",
          "El host se indica con un icono de corona o etiqueta 'Anfitrión'.",
          "La lista se actualiza en tiempo real cuando alguien se une o sale (Socket.io).",
          "Se muestra contador 'X/10 participantes'.",
          "Responsivo: en mobile el panel se abre con botón 'Participantes'.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan componente de participantes.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; Socket.io emite eventos 'user-joined' y 'user-left'.",
          "Heurística 8: Diseño estético y minimalista (solo info relevante).",
        ],
      },
      {
        code: "US-13",
        title: "Copiar enlace de invitación",
        sprint: "S2",
        epic: "E-2 Gestión de reuniones",
        ux: 2,
        design: 3,
        front: 5,
        back: 2,
        description:
          "Como host de una reunión\nQuiero copiar el enlace de invitación al portapapeles\nPara compartirlo fácilmente con otros.",
        acceptanceCriteria: [
          "En /meeting/{meetingId} botón 'Copiar enlace' con icono de clip.",
          "Al hacer clic se copia https://app.com/join/{meetingId} al portapapeles usando Clipboard API.",
          "Se muestra toast 'Enlace copiado' por 2 segundos.",
          "Fallback para navegadores sin Clipboard API: se muestra modal con enlace seleccionado para copiar manualmente.",
          "Accesible con teclado (Enter o Space).",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README actualizados.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; fallback probado en navegadores antiguos.",
          "Heurística 9: Ayudar a reconocer, diagnosticar y recuperarse de errores (feedback claro).",
        ],
      },
      {
        code: "US-14",
        title: "Finalizar reunión (host)",
        sprint: "S2",
        epic: "E-2 Gestión de reuniones",
        ux: 2,
        design: 3,
        front: 5,
        back: 8,
        description:
          "Como host de la reunión\nQuiero finalizar la reunión para todos\nPara cerrar la sesión cuando termine.",
        acceptanceCriteria: [
          "En /meeting/{meetingId} botón 'Finalizar reunión' visible solo para el host.",
          "Al hacer clic se abre modal de confirmación '¿Finalizar para todos?'.",
          "Si confirma, se actualiza status: 'ended' en Firestore meetings/{meetingId}.",
          "Socket.io emite evento 'meeting-ended' a todos los participantes.",
          "Todos los usuarios son redirigidos a /dashboard con toast 'La reunión ha finalizado'.",
          "Se genera resumen del chat con AI y se guarda en summaries/{meetingId}.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan flujo de finalizar reunión.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; integración con AI para resúmenes configurada.",
          "Heurística 10: Ayuda y documentación (confirmación antes de acción crítica).",
        ],
      },
      {
        code: "US-15",
        title: "Salir de reunión (participante)",
        sprint: "S2",
        epic: "E-2 Gestión de reuniones",
        ux: 2,
        design: 2,
        front: 5,
        back: 5,
        description:
          "Como participante de una reunión\nQuiero salir sin finalizarla para otros\nPara abandonar cuando lo necesite.",
        acceptanceCriteria: [
          "En /meeting/{meetingId} botón 'Salir' en la barra de controles.",
          "Al hacer clic se elimina uid de participants[] en Firestore.",
          "Socket.io emite evento 'user-left' con uid.",
          "El usuario es redirigido a /dashboard con toast 'Has salido de la reunión'.",
          "Los demás participantes ven actualizada la lista sin el usuario.",
          "Si el host sale, se asigna nuevo host al primer participante o se finaliza si no hay más.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan flujo de salir de reunión.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; lógica de reasignación de host probada.",
          "WCAG 4: Robusto (funciona en múltiples navegadores).",
        ],
      },
      {
        code: "US-16",
        title: "Enviar mensaje en chat",
        sprint: "S2",
        epic: "E-3 Chat en tiempo real",
        ux: 2,
        design: 5,
        front: 8,
        back: 13,
        description:
          "Como participante de una reunión\nQuiero enviar mensajes de texto\nPara comunicarme sin interrumpir con voz.",
        acceptanceCriteria: [
          "En /meeting/{meetingId} panel de chat con campo de texto y botón 'Enviar'.",
          "Al escribir y presionar Enter o clic en 'Enviar', el mensaje se envía vía Socket.io.",
          "Socket.io emite evento 'chat-message' con {userId, userName, message, timestamp}.",
          "El mensaje se guarda en Firestore meetings/{meetingId}/messages/{messageId}.",
          "Validación: mensaje no vacío, máximo 500 caracteres.",
          "Se muestra en la UI con nombre del usuario, foto y hora.",
          "Manejo de errores: si falla el envío → mensaje marcado como 'No enviado' con botón reintentar.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan implementación de chat.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; Socket.io configurado en backend Render.",
          "Heurística: Visibilidad del estado (indicador 'Escribiendo...').",
        ],
      },
      {
        code: "US-17",
        title: "Recibir mensajes en tiempo real",
        sprint: "S2",
        epic: "E-3 Chat en tiempo real",
        ux: 1,
        design: 3,
        front: 5,
        back: 13,
        description:
          "Como participante de una reunión\nQuiero ver los mensajes de otros instantáneamente\nPara seguir la conversación en vivo.",
        acceptanceCriteria: [
          "Socket.io escucha evento 'chat-message' en el cliente.",
          "Al recibir mensaje, se añade a la lista del chat sin recargar.",
          "Se hace scroll automático al último mensaje.",
          "Se muestra notificación visual si el chat está minimizado.",
          "Los mensajes persisten en Firestore para recuperar historial al unirse.",
          "Al entrar a la reunión se cargan los últimos 50 mensajes desde Firestore.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan flujo de recepción de mensajes.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; historial de mensajes se carga correctamente.",
          "WCAG: Contenido distinguible (contraste adecuado en mensajes).",
        ],
      },
      {
        code: "US-18",
        title: "Ver historial de chat",
        sprint: "S2",
        epic: "E-3 Chat en tiempo real",
        ux: 2,
        design: 3,
        front: 8,
        back: 8,
        description:
          "Como participante que se une tarde\nQuiero ver mensajes anteriores\nPara conocer el contexto de la conversación.",
        acceptanceCriteria: [
          "Al unirse a /meeting/{meetingId}, se ejecuta GET a Firestore meetings/{meetingId}/messages.",
          "Se cargan los últimos 50 mensajes ordenados por timestamp.",
          "Botón 'Cargar más' para obtener mensajes anteriores (paginación).",
          "Los mensajes se muestran con nombre del usuario y hora relativa (ej: 'hace 5 min').",
          "Skeleton loader mientras se cargan mensajes.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README actualizados con carga de historial.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; paginación implementada correctamente.",
          "Heurística: Reconocer, diagnosticar y recuperarse de errores (indicador de carga).",
        ],
      },
      {
        code: "US-19",
        title: "Activar micrófono",
        sprint: "S3",
        epic: "E-4 Transmisión de audio",
        ux: 3,
        design: 5,
        front: 13,
        back: 13,
        description:
          "Como participante de una reunión\nQuiero activar mi micrófono\nPara hablar con los demás participantes.",
        acceptanceCriteria: [
          "En /meeting/{meetingId} botón de micrófono en la barra de controles (icono con estado on/off).",
          "Al hacer clic se solicita permiso de micrófono via navigator.mediaDevices.getUserMedia({audio: true}).",
          "Si se concede, se activa el stream de audio y se conecta con Peer.js.",
          "Se envía stream a todos los peers conectados via WebRTC (full-duplex).",
          "El botón cambia de estado a 'Micrófono activado' con icono verde.",
          "Se muestra indicador visual cuando el usuario está hablando (nivel de audio).",
          "Manejo de errores: permiso denegado → toast 'Permiso de micrófono denegado'; dispositivo no disponible → 'No se detectó micrófono'.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan integración con Peer.js y WebRTC.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; servidor STUN configurado en backend.",
          "WCAG: Operable (controles accesibles por teclado).",
        ],
      },
      {
        code: "US-20",
        title: "Desactivar micrófono",
        sprint: "S3",
        epic: "E-4 Transmisión de audio",
        ux: 1,
        design: 2,
        front: 5,
        back: 3,
        description:
          "Como participante de una reunión\nQuiero desactivar mi micrófono\nPara dejar de transmitir audio temporalmente.",
        acceptanceCriteria: [
          "Al hacer clic en botón de micrófono activo, se detiene el stream de audio local.",
          "Se notifica a todos los peers que el audio está muteado.",
          "El botón cambia a estado 'Micrófono desactivado' con icono rojo y línea diagonal.",
          "El indicador de nivel de audio desaparece.",
          "Los demás participantes ven el estado muteado del usuario en la lista.",
          "Se puede reactivar con un clic (toggle).",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README actualizados con control de mute.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; estados sincronizados correctamente.",
          "Heurística: Control y libertad del usuario (fácil activar/desactivar).",
        ],
      },
      {
        code: "US-21",
        title: "Escuchar audio de otros participantes",
        sprint: "S3",
        epic: "E-4 Transmisión de audio",
        ux: 2,
        design: 5,
        front: 13,
        back: 13,
        description:
          "Como participante de una reunión\nQuiero escuchar el audio de los demás\nPara seguir la conversación en tiempo real.",
        acceptanceCriteria: [
          "Al conectarse a la reunión, Peer.js establece conexiones P2P con todos los participantes.",
          "Se reciben streams de audio via WebRTC y se reproducen automáticamente.",
          "Cada participante tiene control de volumen individual (slider 0-100%).",
          "Se muestra indicador visual cuando alguien está hablando.",
          "Manejo de errores: pérdida de conexión → intenta reconectar automáticamente; falla de STUN → toast 'Problemas de conexión de audio'.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan recepción de audio P2P.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; servidor STUN operativo.",
          "WCAG: Perceptible (alternativas para usuarios con problemas de audio).",
        ],
      },
      {
        code: "US-22",
        title: "Activar cámara",
        sprint: "S4",
        epic: "E-5 Transmisión de video",
        ux: 3,
        design: 8,
        front: 13,
        back: 13,
        description:
          "Como participante de una reunión\nQuiero activar mi cámara\nPara que los demás me vean.",
        acceptanceCriteria: [
          "En /meeting/{meetingId} botón de cámara en la barra de controles (icono con estado on/off).",
          "Al hacer clic se solicita permiso via navigator.mediaDevices.getUserMedia({video: true, audio: false}).",
          "Si se concede, se captura stream de video y se muestra en preview local.",
          "Se envía stream a todos los peers vía WebRTC.",
          "El botón cambia a 'Cámara activada' con icono verde.",
          "Se muestra el video del usuario en la galería de participantes.",
          "Manejo de errores: permiso denegado → toast 'Permiso de cámara denegado'; dispositivo no disponible → 'No se detectó cámara'.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan integración de video con Peer.js.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; servidor STUN secundario configurado.",
          "Heurística: Consistencia y estándares (controles similares a audio).",
        ],
      },
      {
        code: "US-23",
        title: "Desactivar cámara",
        sprint: "S4",
        epic: "E-5 Transmisión de video",
        ux: 1,
        design: 2,
        front: 5,
        back: 3,
        description:
          "Como participante de una reunión\nQuiero desactivar mi cámara\nPara dejar de transmitir video temporalmente.",
        acceptanceCriteria: [
          "Al hacer clic en botón de cámara activa, se detiene el stream de video local.",
          "Se notifica a todos los peers que el video está desactivado.",
          "El botón cambia a 'Cámara desactivada' con icono rojo y línea diagonal.",
          "En la galería se muestra avatar o iniciales del usuario en lugar del video.",
          "Los demás participantes ven el estado del video desactivado.",
          "Se puede reactivar con un clic (toggle).",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README actualizados con control de video.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; estados sincronizados correctamente.",
          "WCAG: Comprensible (iconografía clara).",
        ],
      },
      {
        code: "US-24",
        title: "Ver videos de otros participantes",
        sprint: "S4",
        epic: "E-5 Transmisión de video",
        ux: 3,
        design: 8,
        front: 13,
        back: 13,
        description:
          "Como participante de una reunión\nQuiero ver el video de los demás\nPara tener una experiencia más completa de videoconferencia.",
        acceptanceCriteria: [
          "Se muestran videos de todos los participantes en vista de galería (grid).",
          "Cada video tiene el nombre del participante y estado de audio/video.",
          "En modo presentador, el video activo se muestra grande y los demás en miniaturas.",
          "Se adapta el layout según el número de participantes (1-4: cuadrícula 2x2, 5-9: 3x3, 10: 2 filas).",
          "Si un participante desactiva video, se muestra su avatar.",
          "Responsivo: en mobile se muestra un video a la vez con navegación lateral.",
          "Manejo de errores: pérdida de conexión → intenta reconectar; baja calidad → ajusta bitrate automáticamente.",
        ],
        definitionOfDone: [
          "Todos los criterios de aceptación se cumplen.",
          "JSDoc y README documentan vista de galería y layouts.",
          "Responsivo validado en 320, 768, 1024 px.",
          "Despliegue exitoso; 2 servidores STUN operativos.",
          "Heurística: Diseño estético y minimalista (layout optimizado).",
        ],
      },
    ],
  },
};
